from __future__ import annotations

from typing import Protocol

from app.domain.entities import Lead, RecordStatus, SupportTicket, User, UserRole


class UserRepository(Protocol):
    def get_by_id(self, user_id: str) -> User | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def list_users(self) -> list[User]: ...

    def create_user(self, user: User) -> User: ...

    def update_user(self, user: User) -> User: ...


class LeadRepository(Protocol):
    def create_lead(self, lead: Lead) -> str: ...

    def list_leads(self, *, limit: int, offset: int) -> list[Lead]: ...

    def get_lead(self, lead_id: str) -> Lead | None: ...

    def update_lead_status(self, lead_id: str, status: RecordStatus) -> Lead | None: ...
